In [5]:
# imports
import panel as pn
pn.extension('plotly')
import plotly.express as px
import pandas as pd
import hvplot
import hvplot.pandas
import matplotlib.pyplot as plt
import numpy as np
import os
from pathlib import Path
from dotenv import load_dotenv
import alpaca_trade_api as tradeapi

import warnings
warnings.filterwarnings('ignore')

In [6]:
load_dotenv()

True

In [7]:
alpaca_key = os.getenv('ALPACA_API_KEY')
alpaca_secret = os.getenv('ALPACA_API_SECRET')

alpaca = tradeapi.REST(alpaca_key, alpaca_secret, api_version = "v2")

In [25]:
ticker = ["AAPL", "MSFT"]
timeframe = "1D"
start = pd.Timestamp('2016-05-26', tz = 'US/Pacific').isoformat()
end = pd.Timestamp('2021-05-26', tz = 'US/Pacific').isoformat()

In [32]:
def fetch(tickers):
    timeframe = "1D"
    start = pd.Timestamp('2016-05-26', tz = 'US/Pacific').isoformat()
    end = pd.Timestamp('2021-05-26', tz = 'US/Pacific').isoformat()
    fetch = alpaca.get_barset(
        tickers, 
        timeframe, 
        start = start, 
        end = end
    ).df
    return fetch

In [33]:
fetch(ticker)

                             AAPL                                        \
                             open      high      low   close     volume
time
2021-01-04 00:00:00-05:00  133.52  133.6116  126.760  129.41  123353442
2021-01-05 00:00:00-05:00  128.89  131.7400  128.430  130.95   85139362
2021-01-06 00:00:00-05:00  127.72  131.0499  126.382  126.58  142064548
2021-01-07 00:00:00-05:00  128.36  131.6300  127.860  130.85   95314687
2021-01-08 00:00:00-05:00  132.43  132.6300  130.230  131.99   93211863
...                           ...       ...      ...     ...        ...
2021-05-20 00:00:00-04:00  125.23  127.7200  125.100  127.31   65577507
2021-05-21 00:00:00-04:00  127.85  128.0000  125.210  125.43   69043951
2021-05-24 00:00:00-04:00  126.01  127.9400  125.940  127.10   53894516
2021-05-25 00:00:00-04:00  127.84  128.3200  126.320  126.93   63974536
2021-05-26 00:00:00-04:00  126.93  127.3900  126.420  126.85   47895002

                             MSFT
                             open      high       low   close    volume
time
2021-01-04 00:00:00-05:00  222.53  223.0000  214.8100  217.81  27651582
2021-01-05 00:00:00-05:00  217.26  218.5200  215.7000  218.01  18061458
2021-01-06 00:00:00-05:00  212.17  216.4899  211.9400  212.22  29768110
2021-01-07 00:00:00-05:00  214.04  219.3400  213.7100  218.29  20366208
2021-01-08 00:00:00-05:00  218.68  220.5800  217.0261  219.55  18248721
...                           ...       ...       ...     ...       ...
2021-05-20 00:00:00-04:00  243.85  247.9500  243.8500  246.48  16244463
2021-05-21 00:00:00-04:00  247.56  248.3300  244.7400  245.19  17576230
2021-05-24 00:00:00-04:00  247.77  251.1600  247.5100  250.85  16444165
2021-05-25 00:00:00-04:00  251.65  252.7500  250.8200  251.85  14091454
2021-05-26 00:00:00-04:00  251.28  252.9400  250.7500  251.50  12669689

[100 rows x 10 columns]

In [ ]:
pn.Column()
pn.Column()

In [ ]:
dashboard = pn.Tabs()

In [ ]:
dashboard.servable()