In [43]:
import pandas as pd
import pandas_datareader.data as pdr
% matplotlib inline
from pandas_datareader import data
import datetime as dt
import datetime

UsageError: Line magic function `%` not found.

In [44]:
N = 252

y = datetime.datetime.now() - timedelta(days=N)

y = y.strftime("%m,%d,%Y")

y

'09,26,2020'

In [45]:
x = datetime.datetime.now()

x = x.strftime("%m,%d,%Y")

x

'06,05,2021'

In [46]:
from pandas_datareader import data
from datetime import datetime, timedelta
ticker = 'BTC-USD'
begdate = y
enddate = x
data1 = data.DataReader(ticker,'yahoo', start = begdate, end = enddate)
data1

,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,
2020-08-31,12067.081055,11601.128906,11679.316406,11970.478516,2.731156e+10,11970.478516
2020-09-01,11964.823242,11290.793945,11964.823242,11414.034180,2.803741e+10,11414.034180
2020-09-02,11443.022461,10182.464844,11407.191406,10245.296875,3.192726e+10,10245.296875
2020-09-03,10663.919922,10207.940430,10230.365234,10511.813477,2.996513e+10,10511.813477
2020-09-04,10581.571289,9946.675781,10512.530273,10169.567383,4.491657e+10,10169.567383
...,...,...,...,...,...,...
2021-05-28,37234.500000,33693.929688,35684.156250,34616.066406,4.523101e+10,34616.066406
2021-05-29,36400.667969,33520.738281,34607.406250,35678.128906,3.164608e+10,35678.128906
2021-05-30,37468.250000,34241.945312,35658.593750,37332.855469,3.900985e+10,37332.855469
2021-05-31,37896.734375,35787.085938,37293.792969,36684.925781,3.463942e+10,36684.925781
2021-06-01,38231.339844,35966.308594,36699.921875,37575.179688,3.307087e+10,37575.179688

In [53]:
sp500 = pd.read_csv("S&P500_TICKER_DATA.csv")

In [54]:
sp500

,TICKER,COMPANY,SECTOR,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 246,Unnamed: 247,Unnamed: 248,Unnamed: 249,Unnamed: 250,Unnamed: 251,Unnamed: 252,Unnamed: 253,Unnamed: 254,Unnamed: 255
0,SPY,S&P500 ETF Trust,All,Date,6/4/2020 16:00:00,6/5/2020 16:00:00,6/8/2020 16:00:00,6/9/2020 16:00:00,6/10/2020 16:00:00,6/11/2020 16:00:00,...,5/20/2021 16:00:00,5/21/2021 16:00:00,5/24/2021 16:00:00,5/25/2021 16:00:00,5/26/2021 16:00:00,5/27/2021 16:00:00,5/28/2021 16:00:00,6/1/2021 16:00:00,6/2/2021 16:00:00,6/3/2021 16:00:00
1,NaN,NaN,NaN,Close,311.36,319.34,323.2,320.79,319,300.61,...,415.28,414.94,419.17,418.24,419.07,419.29,420.04,419.67,420.33,418.77
2,ATVI,Activision Blizzard,Communication Services,Date,6/4/2020 16:00:00,6/5/2020 16:00:00,6/8/2020 16:00:00,6/9/2020 16:00:00,6/10/2020 16:00:00,6/11/2020 16:00:00,...,5/20/2021 16:00:00,5/21/2021 16:00:00,5/24/2021 16:00:00,5/25/2021 16:00:00,5/26/2021 16:00:00,5/27/2021 16:00:00,5/28/2021 16:00:00,6/1/2021 16:00:00,6/2/2021 16:00:00,6/3/2021 16:00:00
3,NaN,NaN,NaN,Close,69.81,69.43,70.73,72,73.82,71.28,...,96.57,95.37,96.5,96.57,97.3,97.25,97.25,96.45,95.39,94.98
4,GOOGL,Alphabet Inc. (Class A),Communication Services,Date,6/4/2020 16:00:00,6/5/2020 16:00:00,6/8/2020 16:00:00,6/9/2020 16:00:00,6/10/2020 16:00:00,6/11/2020 16:00:00,...,5/20/2021 16:00:00,5/21/2021 16:00:00,5/24/2021 16:00:00,5/25/2021 16:00:00,5/26/2021 16:00:00,5/27/2021 16:00:00,5/28/2021 16:00:00,6/1/2021 16:00:00,6/2/2021 16:00:00,6/3/2021 16:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1005,NaN,NaN,NaN,Close,57.95,58.45,60.27,59.36,59.2,56.09,...,64.06,64.38,64.42,64.08,63.72,63.66,63.92,63.43,63.9,64.46
1006,WEC,WEC Energy Group,Utilities,Date,6/4/2020 16:00:00,6/5/2020 16:00:00,6/8/2020 16:00:00,6/9/2020 16:00:00,6/10/2020 16:00:00,6/11/2020 16:00:00,...,5/20/2021 16:00:00,5/21/2021 16:00:00,5/24/2021 16:00:00,5/25/2021 16:00:00,5/26/2021 16:00:00,5/27/2021 16:00:00,5/28/2021 16:00:00,6/1/2021 16:00:00,6/2/2021 16:00:00,6/3/2021 16:00:00
1007,NaN,NaN,NaN,Close,92.57,92.85,95.28,93.44,93.71,91.33,...,95.52,96.22,95.36,94.21,93.99,93.35,93.91,92.97,93.18,93.83
1008,XEL,Xcel Energy Inc,Utilities,Date,6/4/2020 16:00:00,6/5/2020 16:00:00,6/8/2020 16:00:00,6/9/2020 16:00:00,6/10/2020 16:00:00,6/11/2020 16:00:00,...,5/20/2021 16:00:00,5/21/2021 16:00:00,5/24/2021 16:00:00,5/25/2021 16:00:00,5/26/2021 16:00:00,5/27/2021 16:00:00,5/28/2021 16:00:00,6/1/2021 16:00:00,6/2/2021 16:00:00,6/3/2021 16:00:00
1009,NaN,NaN,NaN,Close,65.03,65.26,66.95,66.37,66.93,65.08,...,71.58,72.04,71.67,71.24,71,70.27,70.88,70,70.24,70.48

In [55]:
sp500 = sp500.set_index("TICKER")
sp500

,COMPANY,SECTOR,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,...,Unnamed: 246,Unnamed: 247,Unnamed: 248,Unnamed: 249,Unnamed: 250,Unnamed: 251,Unnamed: 252,Unnamed: 253,Unnamed: 254,Unnamed: 255
TICKER,,,,,,,,,,,,,,,,,,,,,
SPY,S&P500 ETF Trust,All,Date,6/4/2020 16:00:00,6/5/2020 16:00:00,6/8/2020 16:00:00,6/9/2020 16:00:00,6/10/2020 16:00:00,6/11/2020 16:00:00,6/12/2020 16:00:00,...,5/20/2021 16:00:00,5/21/2021 16:00:00,5/24/2021 16:00:00,5/25/2021 16:00:00,5/26/2021 16:00:00,5/27/2021 16:00:00,5/28/2021 16:00:00,6/1/2021 16:00:00,6/2/2021 16:00:00,6/3/2021 16:00:00
NaN,NaN,NaN,Close,311.36,319.34,323.2,320.79,319,300.61,304.21,...,415.28,414.94,419.17,418.24,419.07,419.29,420.04,419.67,420.33,418.77
ATVI,Activision Blizzard,Communication Services,Date,6/4/2020 16:00:00,6/5/2020 16:00:00,6/8/2020 16:00:00,6/9/2020 16:00:00,6/10/2020 16:00:00,6/11/2020 16:00:00,6/12/2020 16:00:00,...,5/20/2021 16:00:00,5/21/2021 16:00:00,5/24/2021 16:00:00,5/25/2021 16:00:00,5/26/2021 16:00:00,5/27/2021 16:00:00,5/28/2021 16:00:00,6/1/2021 16:00:00,6/2/2021 16:00:00,6/3/2021 16:00:00
NaN,NaN,NaN,Close,69.81,69.43,70.73,72,73.82,71.28,71.68,...,96.57,95.37,96.5,96.57,97.3,97.25,97.25,96.45,95.39,94.98
GOOGL,Alphabet Inc. (Class A),Communication Services,Date,6/4/2020 16:00:00,6/5/2020 16:00:00,6/8/2020 16:00:00,6/9/2020 16:00:00,6/10/2020 16:00:00,6/11/2020 16:00:00,6/12/2020 16:00:00,...,5/20/2021 16:00:00,5/21/2021 16:00:00,5/24/2021 16:00:00,5/25/2021 16:00:00,5/26/2021 16:00:00,5/27/2021 16:00:00,5/28/2021 16:00:00,6/1/2021 16:00:00,6/2/2021 16:00:00,6/3/2021 16:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
NaN,NaN,NaN,Close,57.95,58.45,60.27,59.36,59.2,56.09,56.17,...,64.06,64.38,64.42,64.08,63.72,63.66,63.92,63.43,63.9,64.46
WEC,WEC Energy Group,Utilities,Date,6/4/2020 16:00:00,6/5/2020 16:00:00,6/8/2020 16:00:00,6/9/2020 16:00:00,6/10/2020 16:00:00,6/11/2020 16:00:00,6/12/2020 16:00:00,...,5/20/2021 16:00:00,5/21/2021 16:00:00,5/24/2021 16:00:00,5/25/2021 16:00:00,5/26/2021 16:00:00,5/27/2021 16:00:00,5/28/2021 16:00:00,6/1/2021 16:00:00,6/2/2021 16:00:00,6/3/2021 16:00:00
NaN,NaN,NaN,Close,92.57,92.85,95.28,93.44,93.71,91.33,90.31,...,95.52,96.22,95.36,94.21,93.99,93.35,93.91,92.97,93.18,93.83
XEL,Xcel Energy Inc,Utilities,Date,6/4/2020 16:00:00,6/5/2020 16:00:00,6/8/2020 16:00:00,6/9/2020 16:00:00,6/10/2020 16:00:00,6/11/2020 16:00:00,6/12/2020 16:00:00,...,5/20/2021 16:00:00,5/21/2021 16:00:00,5/24/2021 16:00:00,5/25/2021 16:00:00,5/26/2021 16:00:00,5/27/2021 16:00:00,5/28/2021 16:00:00,6/1/2021 16:00:00,6/2/2021 16:00:00,6/3/2021 16:00:00
NaN,NaN,NaN,Close,65.03,65.26,66.95,66.37,66.93,65.08,63.65,...,71.58,72.04,71.67,71.24,71,70.27,70.88,70,70.24,70.48

In [50]:
sp500 = sp500.T
sp500

,0,1,2,3,4,5,6,7,8,9,...,1000,1001,1002,1003,1004,1005,1006,1007,1008,1009
TICKER,SPY,NaN,ATVI,NaN,GOOGL,NaN,GOOG,NaN,T,NaN,...,PEG,NaN,SRE,NaN,SO,NaN,WEC,NaN,XEL,NaN
COMPANY,S&P500 ETF Trust,NaN,Activision Blizzard,NaN,Alphabet Inc. (Class A),NaN,Alphabet Inc. (Class C),NaN,AT&T Inc.,NaN,...,Public Service Enterprise Group (PSEG),NaN,Sempra Energy,NaN,Southern Company,NaN,WEC Energy Group,NaN,Xcel Energy Inc,NaN
SECTOR,All,NaN,Communication Services,NaN,Communication Services,NaN,Communication Services,NaN,Communication Services,NaN,...,Utilities,NaN,Utilities,NaN,Utilities,NaN,Utilities,NaN,Utilities,NaN
Unnamed: 3,Date,Close,Date,Close,Date,Close,Date,Close,Date,Close,...,Date,Close,Date,Close,Date,Close,Date,Close,Date,Close
Unnamed: 4,6/4/2020 16:00:00,311.36,6/4/2020 16:00:00,69.81,6/4/2020 16:00:00,1414.3,6/4/2020 16:00:00,1412.18,6/4/2020 16:00:00,31.8,...,6/4/2020 16:00:00,51.94,6/4/2020 16:00:00,128.79,6/4/2020 16:00:00,57.95,6/4/2020 16:00:00,92.57,6/4/2020 16:00:00,65.03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Unnamed: 251,5/27/2021 16:00:00,419.29,5/27/2021 16:00:00,97.25,5/27/2021 16:00:00,2362.68,5/27/2021 16:00:00,2402.51,5/27/2021 16:00:00,29.71,...,5/27/2021 16:00:00,62.03,5/27/2021 16:00:00,135.3,5/27/2021 16:00:00,63.66,5/27/2021 16:00:00,93.35,5/27/2021 16:00:00,70.27
Unnamed: 252,5/28/2021 16:00:00,420.04,5/28/2021 16:00:00,97.25,5/28/2021 16:00:00,2356.85,5/28/2021 16:00:00,2411.56,5/28/2021 16:00:00,29.43,...,5/28/2021 16:00:00,62.12,5/28/2021 16:00:00,135.49,5/28/2021 16:00:00,63.92,5/28/2021 16:00:00,93.91,5/28/2021 16:00:00,70.88
Unnamed: 253,6/1/2021 16:00:00,419.67,6/1/2021 16:00:00,96.45,6/1/2021 16:00:00,2381.18,6/1/2021 16:00:00,2429.81,6/1/2021 16:00:00,29.32,...,6/1/2021 16:00:00,62.03,6/1/2021 16:00:00,135.93,6/1/2021 16:00:00,63.43,6/1/2021 16:00:00,92.97,6/1/2021 16:00:00,70
Unnamed: 254,6/2/2021 16:00:00,420.33,6/2/2021 16:00:00,95.39,6/2/2021 16:00:00,2370.59,6/2/2021 16:00:00,2421.28,6/2/2021 16:00:00,29.61,...,6/2/2021 16:00:00,61.67,6/2/2021 16:00:00,135.84,6/2/2021 16:00:00,63.9,6/2/2021 16:00:00,93.18,6/2/2021 16:00:00,70.24
Unnamed: 255,6/3/2021 16:00:00,418.77,6/3/2021 16:00:00,94.98,6/3/2021 16:00:00,2347.58,6/3/2021 16:00:00,2404.61,6/3/2021 16:00:00,29.23,...,6/3/2021 16:00:00,61.71,6/3/2021 16:00:00,137.01,6/3/2021 16:00:00,64.46,6/3/2021 16:00:00,93.83,6/3/2021 16:00:00,70.48